### PR TITLE
bug fix for searching incorrect address (#77)

### LINKED ISSUE #77: Address search fires incorrectly when selecting from duplicate street addresses
Addresses shown in the autosuggest dropdown that share the same number and street name but a different borough can potentially show an incorrect search result after being selected.

For example, search for "52 Henry St", select the Manhattan address and the app displays the Brooklyn address instead.

### PR DESCRIPTION
**Pull request by clhenrick**
Fixes #77 

TODO:

- [x] update unit tests

Instead of always making a request to the GeoSearch `search` API endpoint when the user submits the address search form, check if a user selected an address from the auto-suggestions list. If so then pass that list item's data to the rent-stabilized search as well as store its location data for displaying in the search result map.

### CODE REVIEW

File: app/src/action_creators/searchRentStabilizedActions.js [hunk 1]
```diff
@@ -33,20 +36,34 @@ export function getBBL(feature) {
 
 /**
  * searchRentStabilized
+ * @param {string | object } address The address to be searched
```
Comment (clhenrick) [inline app/src/action_creators/searchRentStabilizedActions.js:39]: param name should be `addressInfo`

File: app/yarn.lock [hunk 2]
```diff
@@ -2478,9 +2478,9 @@ caniuse-api@^3.0.0:
     lodash.uniq "^4.5.0"
 
 caniuse-lite@^1.0.0, caniuse-lite@^1.0.30001109, caniuse-lite@^1.0.30001111:
-  version "1.0.30001117"
-  resolved "https://registry.yarnpkg.com/caniuse-lite/-/caniuse-lite-1.0.30001117.tgz#69a9fae5d480eaa9589f7641a83842ad396d17c4"
-  integrity sha512-4tY0Fatzdx59kYjQs+bNxUwZB03ZEBgVmJ1UkFPz/Q8OLiUUbjct2EdpnXj0fvFTPej2EkbPIG0w8BWsjAyk1Q==
+  version "1.0.30001180"
+  resolved "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001180.tgz"
+  integrity sha512-n8JVqXuZMVSPKiPiypjFtDTXc4jWIdjxull0f92WLo7e1MSi3uJ3NvveakSh/aCl1QKFAvIz3vIj0v+0K+FrXw==
```
Comment (clhenrick) [inline app/yarn.lock:2483]: Remove this commit as it's a dependency update and not part of this bug fix. Can cherry pick it into master after.

Comment (clhenrick) [reply app/yarn.lock]: Run `npx browserslist@latest --update-db` to recreate
